language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-411073985
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install: pip install tox-travis coverage codacy-coverage

script: tox

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
